name: Eagle
icon: 🦅
weightInKilograms: 6
maxAnimalsPerCell: 20
maxMovementSpeedPerTurn: 3
foodRequiredForFullSatiation: 1
predationProbability:
  Wolf: 0
  Snake: 0
  Fox: 10
  Bear: 0
  Horse: 0
  Deer: 0
  Rabbit: 90
  Mouse: 90
  Goat: 0
  Sheep: 0
  Boar: 0
  Buffalo: 0
  Duck: 80
  Caterpillar: 0
  Plants: 0