name: Fox
weightInKilograms: 8
maxAnimalsPerCell: 30
maxMovementSpeedPerTurn: 2
foodRequiredForFullSatiation: 2
predationProbability:
  Wolf: 0
  Snake: 0
  Bear: 0
  Eagle: 0
  Horse: 0
  Deer: 0
  Rabbit: 70
  Mouse: 90
  Goat: 0
  Sheep: 0
  Boar: 0
  Buffalo: 0
  Duck: 60
  Caterpillar: 40
  Plants: 0