name: Snake
icon: 🐍
weightInKilograms: 15
maxAnimalsPerCell: 30
maxMovementSpeedPerTurn: 1
foodRequiredForFullSatiation: 3
predationProbability:
  Wolf: 0
  Fox: 15
  Bear: 0
  Eagle: 0
  Horse: 0
  Deer: 0
  Rabbit: 20
  Mouse: 40
  Goat: 0
  Sheep: 0
  Boar: 0
  Buffalo: 0
  Duck: 10
  Caterpillar: 0
  Plants: 0