name: Boar
weightInKilograms: 400
maxAnimalsPerCell: 50
maxMovementSpeedPerTurn: 2
foodRequiredForFullSatiation: 50
predationProbability:
  Wolf: 0
  Snake: 0
  Fox: 0
  Bear: 0
  Eagle: 0
  Horse: 0
  Deer: 0
  Rabbit: 0
  Mouse: 50
  Goat: 0
  Sheep: 0
  Buffalo: 0
  Duck: 0
  Caterpillar: 90
  Plants: 100

