name: Caterpillar
weightInKilograms: 0.01
maxAnimalsPerCell: 1000
maxMovementSpeedPerTurn: 0
foodRequiredForFullSatiation: 0
predationProbability:
  Wolf: 0
  Snake: 0
  Fox: 0
  Bear: 0
  Eagle: 0
  Horse: 0
  Deer: 0
  Rabbit: 0
  Mouse: 0
  Goat: 0
  Sheep: 0
  Boar: 0
  Buffalo: 0
  Duck: 0
  Plants: 100




