name: Deer
icon: 🦌
weightInKilograms: 300
maxAnimalsPerCell: 20
maxMovementSpeedPerTurn: 4
foodRequiredForFullSatiation: 50
predationProbability:
  Wolf: 0
  Snake: 0
  Fox: 0
  Bear: 0
  Eagle: 0
  Horse: 0
  Rabbit: 0
  Mouse: 0
  Goat: 0
  Sheep: 0
  Boar: 0
  Buffalo: 0
  Duck: 0
  Caterpillar: 0
  Plants: 100
